# Generated by Django 2.2.4 on 2020-02-27 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contactmsg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=300)),
                ('lastname', models.CharField(max_length=300)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=300)),
                ('message', models.CharField(max_length=3000)),
                ('subtime', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['subtime'],
            },
        ),
    ]
