# Generated by Django 2.2.4 on 2020-02-27 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmsg',
            name='subtime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
