# Generated by Django 2.2.4 on 2020-02-27 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_auto_20200227_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmsg',
            name='subtime',
            field=models.DateTimeField(),
        ),
    ]
