# Generated by Django 2.0.7 on 2018-08-25 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_registration',
            name='question',
        ),
    ]
